### ISSUE TITLE
java error occured when reading grib2 file with nctoolbox

### ISSUE THREAD

**Issue by xiaoxj** [xiaoxj/java-error-occured-when-reading-grib2-file-with-nctoolbox#1]
I have downloaded the nctoolbox(nctoolbox-1.1.0) to read the grib2 file from http://nomads.ncep.noaa.gov/pub/data/nccf/com/cfs/prod/cfs/cfs.20160308/00/6hrly_grib_01/. The java error occured when I run the ncgeodataset. My matlab version is 8.1.0.604 (R2013a). Coule you help me? The error information will be list below.
nc = ncgeodataset('flxf2016030800.01.2016030800.grb2');
2016-03-15 11:51:06,389 [main] WARN  ucar.nc2.grib.grib2.Grib2Index  - Grib2Index bad size = -1 for flxf2016030800.01.2016030800.grb2 index = flxf2016030800.01.2016030800.grb2.gbx9

Error using ncdataset (line 91)
Failed to open flxf2016030800.01.2016030800.grb2

Error in cfdataset (line 55)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 20)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 75)
    Java exception occurred:
    java.io.IOException: java.lang.RuntimeException: java.lang.VerifyError:
    ucar/nc2/grib/grib2/Grib2IndexProto$Grib2Index

```
    at ucar.nc2.NetcdfFile.open(NetcdfFile.java:425)

    at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:699)

    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:421)

    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:404)

    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:389)

    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:376)

Caused by: java.lang.RuntimeException: java.lang.VerifyError: ucar/nc2/grib/grib2/Grib2IndexProto$Grib2Index

    at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1557)

    at ucar.nc2.NetcdfFile.open(NetcdfFile.java:813)

    at ucar.nc2.NetcdfFile.open(NetcdfFile.java:422)

    ... 5 more

Caused by: java.lang.VerifyError: ucar/nc2/grib/grib2/Grib2IndexProto$Grib2Index

    at ucar.nc2.grib.grib2.Grib2Index.makeIndex(Grib2Index.java:233)

    at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:111)

    at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:311)

    at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1521)

    ... 7 more
```

**Comment by zyn4624** [comment]
hi, does your problem have been solved ?
